"""creating initial relations

Revision ID: 1dabc852f944
Revises: 5221143c1665
Create Date: 2025-12-10 21:36:49.864394

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.sql import table, column

# revision identifiers, used by Alembic.
revision: str = '1dabc852f944'
down_revision: Union[str, Sequence[str], None] = '5221143c1665'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
        schema='events_finder'
    )

    category_table = table(
        'category',
        column('name', sa.Text()),
        schema='events_finder'
    )

    categories = [
        { "name": "Закрытие задолженностей" },
        { "name": "Химия" },
        { "name": "Наука" },
        { "name": "Клуб наставников" },
        { "name": "Глубокое обучение" },
        { "name": "Backend-разработка" },
        { "name": "Экономика" },
        { "name": "Frontend разработка" },
        { "name": "IOS-разработка" },
        { "name": "Музыка" },
        { "name": "Туризм" },
        { "name": "DevOps" },
        { "name": "Робототехника" },
        { "name": "Волонтерство" },
        { "name": "Хакатоны" },
        { "name": "Иностранные языки" },
        { "name": "Вокал" },
        { "name": "Android-разработка" },
        { "name": "3D-моделирование" },
        { "name": "Промышленный дизайн" },
        { "name": "Физика" },
        { "name": "Стажировки" },
        { "name": "Танцы" },
        { "name": "Машинное обучение" },
        { "name": "Творчество" },
        { "name": "Театр" },
        { "name": "Спортивное программирование" },
        { "name": "Предпринимательство" },
        { "name": "Интеллектуальные игры" },
        { "name": "Анализ данных и Big Data" },
        { "name": "Гейм-дизайн" },
        { "name": "Кибербезопасность" },
        { "name": "Спорт" },
        { "name": "КВН" },
        { "name": "Дизайн" },
    ]

    op.bulk_insert(category_table, categories)

    op.create_table('photo',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='events_finder'
    )
    op.create_table('team',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='events_finder'
    )
    op.create_table('telegram_info',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.Text(), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chat_id'),
    sa.UniqueConstraint('telegram_id'),
    sa.UniqueConstraint('username'),
    schema='events_finder'
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('telegram_id', sa.Integer(), nullable=True),
    sa.Column('first_name', sa.Text(), nullable=False),
    sa.Column('last_name', sa.Text(), nullable=False),
    sa.Column('photo_id', sa.Integer(), nullable=True),
    sa.Column('balance', sa.Integer(), nullable=False),
    sa.Column('role', postgresql.ENUM('PARTICIPANT', 'ADMIN', 'ORGANISER', 'DISTRIBUTOR', name='user_role'), nullable=False),
    sa.Column('longitude', sa.DECIMAL(precision=8, scale=6), nullable=False),
    sa.Column('latitude', sa.DECIMAL(precision=9, scale=6), nullable=False),
    sa.ForeignKeyConstraint(['photo_id'], ['events_finder.photo.id'], ),
    sa.ForeignKeyConstraint(['telegram_id'], ['events_finder.telegram_info.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='events_finder'
    )
    op.create_table('event',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('longitude', sa.DECIMAL(precision=8, scale=6), nullable=False),
    sa.Column('latitude', sa.DECIMAL(precision=9, scale=6), nullable=False),
    sa.Column('age_restriction', sa.Integer(), nullable=False),
    sa.Column('chat_link', sa.Text(), nullable=False),
    sa.Column('organiser_id', sa.Integer(), nullable=True),
    sa.Column('max_participants', sa.Integer(), nullable=False),
    sa.Column('cost', sa.Integer(), nullable=False),
    sa.Column('balance', sa.Integer(), nullable=False),
    sa.Column('is_freezed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['organiser_id'], ['events_finder.user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='events_finder'
    )
    op.create_table('user_ban',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_ban_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_ban_id'], ['events_finder.user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['events_finder.user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'user_ban_id'),
    sa.UniqueConstraint('user_id', 'user_ban_id'),
    schema='events_finder'
    )
    op.create_table('user_category',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['events_finder.category.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['events_finder.user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'category_id'),
    sa.UniqueConstraint('user_id', 'category_id'),
    schema='events_finder'
    )
    op.create_table('user_report',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('reported_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['reported_user_id'], ['events_finder.user.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['events_finder.user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='events_finder'
    )
    op.create_table('user_team',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['events_finder.team.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['events_finder.user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'team_id'),
    sa.UniqueConstraint('user_id', 'team_id'),
    schema='events_finder'
    )
    op.create_table('event_category',
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['events_finder.category.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['events_finder.event.id'], ),
    sa.PrimaryKeyConstraint('event_id', 'category_id'),
    sa.UniqueConstraint('event_id', 'category_id'),
    schema='events_finder'
    )
    op.create_table('event_photo',
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('photo_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events_finder.event.id'], ),
    sa.ForeignKeyConstraint(['photo_id'], ['events_finder.photo.id'], ),
    sa.PrimaryKeyConstraint('event_id', 'photo_id'),
    sa.UniqueConstraint('event_id', 'photo_id'),
    schema='events_finder'
    )
    op.create_table('event_report',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('reported_event_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['reported_event_id'], ['events_finder.event.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['events_finder.user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='events_finder'
    )
    op.create_table('ticket',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('status', postgresql.ENUM('PENDING', 'ACCEPTED', 'DELETED', name='ticket_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events_finder.event.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['events_finder.user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'event_id'),
    schema='events_finder'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ticket', schema='events_finder')
    op.drop_table('event_report', schema='events_finder')
    op.drop_table('event_photo', schema='events_finder')
    op.drop_table('event_category', schema='events_finder')
    op.drop_table('user_team', schema='events_finder')
    op.drop_table('user_report', schema='events_finder')
    op.drop_table('user_category', schema='events_finder')
    op.drop_table('user_ban', schema='events_finder')
    op.drop_table('event', schema='events_finder')
    op.drop_table('user', schema='events_finder')
    op.drop_table('telegram_info', schema='events_finder')
    op.drop_table('team', schema='events_finder')
    op.drop_table('photo', schema='events_finder')
    op.drop_table('category', schema='events_finder')
    # ### end Alembic commands ###
