name: Build and Deploy
on:
  push:
    branches: [ main, release, develop ]
  pull_request:
    branches: [ main, release, develop ]
  workflow_dispatch:


jobs:
  Build_nginx:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    env:
      job_name: Build_Job
      IMAGE_TAG_NGINX: ${{secrets.PACKAGE_LINK}}/nginx:latest
      nginx_container: events_finder-nginx
    steps:
    - uses: actions/checkout@v4
    - name: Login ghcr.io
      run: |
        echo ${{ secrets.PAT }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
    - name: Build docker images
      run: |
        docker compose build nginx
    - name: Push docker images
      run: |
        docker images
        docker tag $nginx_container ${{ env.IMAGE_TAG_NGINX }}
        docker push ${{ env.IMAGE_TAG_NGINX }}

    - name: Verify push manually
      run: |
        docker pull ${{ env.IMAGE_TAG_NGINX }} || echo "Image backend not available for pull"

  Build_backend:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    env:
      job_name: Build_Job
      IMAGE_TAG_BACK: ${{secrets.PACKAGE_LINK}}/backend:latest
      backend_container: events_finder-backend
    steps:
    - uses: actions/checkout@v4
    - name: Login ghcr.io
      run: |
        echo ${{ secrets.PAT }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
    - name: Build docker images
      run: |
        docker compose build backend
    - name: Push docker images
      run: |
        docker images
        docker tag $backend_container ${{ env.IMAGE_TAG_BACK }}
        docker push ${{ env.IMAGE_TAG_BACK }}

    - name: Verify push manually
      run: |
        docker pull ${{ env.IMAGE_TAG_BACK }} || echo "Image backend not available for pull"

  Build_recommender_system:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    env:
      job_name: Build_Job
      IMAGE_TAG_BACK: ${{secrets.PACKAGE_LINK}}/recommender_system:latest
      backend_container: events_finder-recommender_system
    steps:
    - uses: actions/checkout@v4
    - name: Login ghcr.io
      run: |
        echo ${{ secrets.PAT }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
    - name: Build docker images
      run: |
        docker compose build recommender_system
    - name: Push docker images
      run: |
        docker images
        docker tag $rec_sys_container ${{ env.IMAGE_TAG_BACK }}
        docker push ${{ env.IMAGE_TAG_BACK }}

    - name: Verify push manually
      run: |
        docker pull ${{ env.IMAGE_TAG_BACK }} || echo "Image backend not available for pull"

  Build_bot:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    env:
      job_name: Build_Job
      IMAGE_TAG_BACK: ${{secrets.PACKAGE_LINK}}/bot:latest
      backend_container: events_finder-bot
    steps:
    - uses: actions/checkout@v4
    - name: Login ghcr.io
      run: |
        echo ${{ secrets.PAT }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
    - name: Build docker images
      run: |
        docker compose build bot
    - name: Push docker images
      run: |
        docker images
        docker tag $bot_container ${{ env.IMAGE_TAG_BACK }}
        docker push ${{ env.IMAGE_TAG_BACK }}

    - name: Verify push manually
      run: |
        docker pull ${{ env.IMAGE_TAG_BACK }} || echo "Image backend not available for pull"

  Build_ml_classifier:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    env:
      job_name: Build_Job
      IMAGE_TAG_BACK: ${{secrets.PACKAGE_LINK}}/ml_classifier:latest
      backend_container: events_finder-ml_classifier
    steps:
    - uses: actions/checkout@v4
    - name: Login ghcr.io
      run: |
        echo ${{ secrets.PAT }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
    - name: Build docker images
      run: |
        docker compose build ml_classifier
    - name: Push docker images
      run: |
        docker images
        docker tag $bot_container ${{ env.IMAGE_TAG_BACK }}
        docker push ${{ env.IMAGE_TAG_BACK }}

    - name: Verify push manually
      run: |
        docker pull ${{ env.IMAGE_TAG_BACK }} || echo "Image backend not available for pull"

  Pull_nginx:
    runs-on: ubuntu-latest
    needs: Build_nginx
    env:
      job_name: Deploy_Job
    steps:
    - uses: actions/checkout@v4
    - name: Setup ssh
      run: |
        mkdir -p ~/.ssh
        touch ~/.ssh/id_rsa
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
    - name: Connect SSH to server and setup
      run: |
        echo "${{secrets.SSH_USER}}@${{secrets.SSH_HOST}}"
        ssh -o StrictHostKeyChecking=no ${{secrets.SSH_USER}}@${{secrets.SSH_HOST}} "
            mkdir -p ~/app
            mkdir -p ~/app/nginx/conf.d
            cd ~/app
            touch .env
            echo "PACKAGE_LINK=${{secrets.PACKAGE_LINK}}" > .env
        "
        scp -o StrictHostKeyChecking=no docker-compose-deploy.yaml ${{secrets.SSH_USER}}@${{secrets.SSH_HOST}}:~/app/
        scp -o StrictHostKeyChecking=no ./nginx/nginx.conf ${{secrets.SSH_USER}}@${{secrets.SSH_HOST}}:~/app/nginx/
    - name: Pull on server
      run: |
        ssh -o StrictHostKeyChecking=no ${{secrets.SSH_USER}}@${{secrets.SSH_HOST}} "
            cd ~/app
            echo ${{ secrets.PAT }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            docker compose -f docker-compose-deploy.yaml pull nginx
        "

  Pull_backend:
    runs-on: ubuntu-latest
    needs:
    - Build_backend
    env:
      job_name: Deploy_Job
    steps:
    - uses: actions/checkout@v4
    - name: Setup ssh
      run: |
        mkdir -p ~/.ssh
        touch ~/.ssh/id_rsa
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
    - name: Connect SSH to server and setup
      run: |
        echo "${{secrets.SSH_USER}}@${{secrets.SSH_HOST}}"
        ssh -o StrictHostKeyChecking=no ${{secrets.SSH_USER}}@${{secrets.SSH_HOST}} "
            mkdir -p ~/app
            cd ~/app
            touch .env
            echo "PACKAGE_LINK=${{secrets.PACKAGE_LINK}}" > .env
        "
        scp -o StrictHostKeyChecking=no docker-compose-deploy.yaml ${{secrets.SSH_USER}}@${{secrets.SSH_HOST}}:~/app/
    - name: Pull on server
      run: |
        ssh -o StrictHostKeyChecking=no ${{secrets.SSH_USER}}@${{secrets.SSH_HOST}} "
            cd ~/app
            echo ${{ secrets.PAT }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            docker compose -f docker-compose-deploy.yaml pull backend
        "

  Pull_bot:
    runs-on: ubuntu-latest
    needs:
    - Build_bot
    env:
      job_name: Deploy_Job
    steps:
    - uses: actions/checkout@v4
    - name: Setup ssh
      run: |
        mkdir -p ~/.ssh
        touch ~/.ssh/id_rsa
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
    - name: Connect SSH to server and setup
      run: |
        echo "${{secrets.SSH_USER}}@${{secrets.SSH_HOST}}"
        ssh -o StrictHostKeyChecking=no ${{secrets.SSH_USER}}@${{secrets.SSH_HOST}} "
            mkdir -p ~/app
            cd ~/app
            touch .env
            echo "PACKAGE_LINK=${{secrets.PACKAGE_LINK}}" > .env
        "
        scp -o StrictHostKeyChecking=no docker-compose-deploy.yaml ${{secrets.SSH_USER}}@${{secrets.SSH_HOST}}:~/app/
    - name: Pull on server
      run: |
        ssh -o StrictHostKeyChecking=no ${{secrets.SSH_USER}}@${{secrets.SSH_HOST}} "
            cd ~/app
            echo ${{ secrets.PAT }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            docker compose -f docker-compose-deploy.yaml pull bot
        "

  Pull_recommender_system:
    runs-on: ubuntu-latest
    needs:
    - Build_recommender_system
    env:
      job_name: Deploy_Job
    steps:
    - uses: actions/checkout@v4
    - name: Setup ssh
      run: |
        mkdir -p ~/.ssh
        touch ~/.ssh/id_rsa
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
    - name: Connect SSH to server and setup
      run: |
        echo "${{secrets.SSH_USER}}@${{secrets.SSH_HOST}}"
        ssh -o StrictHostKeyChecking=no ${{secrets.SSH_USER}}@${{secrets.SSH_HOST}} "
            mkdir -p ~/app
            cd ~/app
            touch .env
            echo "PACKAGE_LINK=${{secrets.PACKAGE_LINK}}" > .env
        "
        scp -o StrictHostKeyChecking=no docker-compose-deploy.yaml ${{secrets.SSH_USER}}@${{secrets.SSH_HOST}}:~/app/
    - name: Pull on server
      run: |
        ssh -o StrictHostKeyChecking=no ${{secrets.SSH_USER}}@${{secrets.SSH_HOST}} "
            cd ~/app
            echo ${{ secrets.PAT }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            docker compose -f docker-compose-deploy.yaml pull recommender_system
        "

  Pull_ml_classifier:
    runs-on: ubuntu-latest
    needs:
    - Build_ml_classifier
    env:
      job_name: Deploy_Job
    steps:
    - uses: actions/checkout@v4
    - name: Setup ssh
      run: |
        mkdir -p ~/.ssh
        touch ~/.ssh/id_rsa
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
    - name: Connect SSH to server and setup
      run: |
        echo "${{secrets.SSH_USER}}@${{secrets.SSH_HOST}}"
        ssh -o StrictHostKeyChecking=no ${{secrets.SSH_USER}}@${{secrets.SSH_HOST}} "
            mkdir -p ~/app
            cd ~/app
            touch .env
            echo "PACKAGE_LINK=${{secrets.PACKAGE_LINK}}" > .env
        "
        scp -o StrictHostKeyChecking=no docker-compose-deploy.yaml ${{secrets.SSH_USER}}@${{secrets.SSH_HOST}}:~/app/
    - name: Pull on server
      run: |
        ssh -o StrictHostKeyChecking=no ${{secrets.SSH_USER}}@${{secrets.SSH_HOST}} "
            cd ~/app
            echo ${{ secrets.PAT }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            docker compose -f docker-compose-deploy.yaml pull ml_classifier
        "

  Deploy:
    runs-on: ubuntu-latest
    needs:
    - Pull_backend
    - Pull_nginx
    env:
      job_name: Deploy_Job
    steps:
    - uses: actions/checkout@v4
    - name: Setup ssh
      run: |
        mkdir -p ~/.ssh
        touch ~/.ssh/id_rsa
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
    - name: Connect SSH to server and setup
      run: |
        echo "${{secrets.SSH_USER}}@${{secrets.SSH_HOST}}"
        ssh -o StrictHostKeyChecking=no ${{secrets.SSH_USER}}@${{secrets.SSH_HOST}} "
            mkdir -p ~/app
            cd ~/app
            touch .env
            echo "PACKAGE_LINK=${{secrets.PACKAGE_LINK}}" > .env
        "
        scp -o StrictHostKeyChecking=no docker-compose-deploy.yaml ${{secrets.SSH_USER}}@${{secrets.SSH_HOST}}:~/app/
    - name: Deploy on server
      run: |
        ssh -o StrictHostKeyChecking=no ${{secrets.SSH_USER}}@${{secrets.SSH_HOST}} "
            cd ~/app
            echo ${{ secrets.PAT }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            docker compose -f docker-compose-deploy.yaml down
            docker compose -f docker-compose-deploy.yaml up -d
        "
